### ISSUE TITLE
Literal datatype notation in query

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/HDT-Node#10]
In HDT-Node, the query syntax for a datatyped-literal is `"val"^^http://datatype`. In the HDT-CLI, the syntax is `"val"^^<http://datatype>`.
I get the motivation for HDT-Node to remove the angular brackets, as regular IRIs don't have these as well and you'd like to present a consistent API to the user. 
I get the impression though that this representation only makes it more confusing (at least it does for me), for the following reasons:

- The HDT cli _does_ require angular brackets
- Parsing the literal using common libs is not possible, it's not standards compliant
- The inclusion of quotes in a literal implies that we're seeing a standard serialized term. (I know that these quotes are required to be able to differentiate between IRIs and literals. Still, it's confusing ;) )

Any thoughts?

**Comment by RubenVerborgh** [comment]
Hi @LaurensRietveld, in time (and I hope soon), we'll migrate to [RDF/JS](https://cdn.rawgit.com/rdfjs/representation-task-force/96009c29/interface-spec.html) for the JavaScript interface, so this issue will become obsolete. Nonetheless, an answer is below.

> I get the motivation for HDT-Node to remove the angular brackets, as regular IRIs don't have these as well and you'd like to present a consistent API to the user.

That motivation was actually different: I follow [what N3.js uses for triple representation](https://github.com/RubenVerborgh/N3.js/tree/v0.11.1#triple-representation).

> The HDT cli does require angular brackets

Fair enough, but then again, no reason for the CLI to use the N3.js representation (as this library does).

> Parsing the literal using common libs is not possible, it's not standards compliant

That is not possible anyway, because in addition to the missing angular brackets, no escaping happens. I.e., the 3-character string `"\"` is represented as `""\"`

> The inclusion of quotes in a literal implies that we're seeing a standard serialized term

Wrong implication 😉  The README [explains](https://github.com/RubenVerborgh/HDT-Node#searching-for-triples-matching-apattern) how the literals need to be interpreted.

----

In any case, all of the confusion will disappear when we adopt RDF/JS.
